### ISSUE TITLE
在4:3屏幕上显示不正确的问题

### ISSUE THREAD

**Issue by 2551269702** [kamiya-dev/kamiya#11]
![49A92BF4-615F-4B88-9E91-36197A83E848](https://user-images.githubusercontent.com/88941547/205415964-d6294c9c-5103-4cbe-9478-e59bbfb7555b.jpeg)

**Comment by 2551269702** [comment]
以及一些建议
![DD16483A-DE65-4FF9-8164-FE7BDF6C697F](https://user-images.githubusercontent.com/88941547/205416482-4b4e8b7a-8d8f-4d02-a917-9eb0d6c77455.jpeg)
![DB9B8FEE-B696-47DE-9E10-0A4631E0E73C](https://user-images.githubusercontent.com/88941547/205416504-b2925202-2c58-4416-928c-48c45687e06c.jpeg)

**Comment by haojie06** [comment]
感谢反馈，注册这个我们之后应该是会改为使用帐号密码的方式，这个只是暂时留在这里。
